version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis.development.local
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
      - redis-config:/usr/local/etc/redis
    environment:
      - REDIS_PASSWORD=Aa123456
      - REDIS_PORT=6379
      - REDIS_DATABASES=16

volumes:
  redis-data:
  redis-config:
